<div id="content">
    <noscript style="color: white; text-align: center; position: absolute; width: 100%; z-index: 30; margin-top: 2em">
        <p>It seems that your browser does not support JavaScript (or JavaScript support is disabled).<br/>
        You can't enjoy the full-featured slideshow in this condition.<br/>
        Either enable JavaScript, or click <a href="$next$">here</a> for an alternate, simpler slideshow.<br/>
        Click <a href="$home$">here</a> to go back.</p>
    </noscript>
    <div id="initialLoadingWidget" >
    </div>
    <div id="slideshow">
    </div>
    <div id="lightbox">
        <span id="navigationCloseWidget"> </span>
        <div id="thumbnails">
        </div>
    </div>
    <div id="imageOverlay">
        <div id="waitingWidget">
        </div>
        <div id="loadingWidget">
        </div>
    </div>
</div>
