<div id="pageFB">
    <div id="contentFB">
        <div id="slideshowFB">
            <div id="fancybox-buttons" class="top">
                <ul>
                    <li><a class="btnPrev" id="navigationPreviousWidget" href="$previous$"></a></li>
                    <li><a class="btnLightbox" id="navigationLightBoxWidget" href="$lightbox$"></a></li>
                    <li><a class="btnClose" id="navigationHomeWidget" href="$home$"></a></li>
                    <li><a class="btnNext" id="navigationNextWidget" href="$next$"></a></li>
                </ul>
            </div>
            <div id="imageRendererFB">
                <div id="divimageFB"><img id="imageFB" src="$imageUrl$" /></div>
            </div>
            <div id="title1">$caption$</div>
        <div id="copyright">$copyright$</div>
        </div>
    </div>
</div>
